import menuIcon from './menu.png'
import copyIcon from './copy.png'
import homeIcon from './home.png'
import wealthIcon from './wealth.png'
import planIcon from './plan.png'
import communityIcon from './community.png'
import languageIcon from './language.png'
import enusIcon from './enus.png'
import enznIcon from './enzn.png'
import level0Icon from './level0.png'
import level1Icon from './level1.png'
import level2Icon from './level2.png'
import level3Icon from './level3.png'
import level4Icon from './level4.png'
import level5Icon from './level5.png'
import level6Icon from './level6.png'
import level7Icon from './level7.png'
import labor5Icon from './labor5.png'
import labor6Icon from './labor6.png'
import labor7Icon from './labor7.png'
import ipoIcon from './ipo.png'
import ecologyIcon from './ecology.png'
import cardIcon from './card.png'
import startIcon from './start.png';
import moonIcon from './moon.png';
import earthIcon from './earth.png';
import sunIcon from './sun.png';
import bannerIcon from './banner.png';
import bannerIcon1 from './banner1.png';

export { menuIcon, copyIcon, homeIcon, wealthIcon, planIcon, communityIcon, languageIcon, enusIcon, enznIcon, level0Icon, level1Icon, level2Icon, level3Icon, level4Icon, level5Icon, level6Icon, level7Icon, labor5Icon, labor6Icon, labor7Icon, ipoIcon, ecologyIcon, cardIcon, startIcon, moonIcon, earthIcon, sunIcon, bannerIcon, bannerIcon1 }